### ISSUE TITLE
Error when trying to install citation chaser

### ISSUE THREAD

**Issue by bradleymecham** [nealhaddaway/citationchaser#10]
Currently getting this error :-/  Using devtools install_github("nealhaddaway/citationchaser"), R 4.0.0

Error: Failed to install 'citationchaser' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * checking DESCRIPTION meta-information ... ERROR
E> Malformed Authors@R field:
E>   <text>:6:53: unexpected ','
E> 5:          email = "nealhaddaway@gmail.com",
E> 6:          comment = c(ORCID = "0000-0003-3902-2234")),
E>                                                        ^
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.

**Comment by nealhaddaway** [comment]
Great spot, thanks! I've fixed the typo in the DESCRIPTION file and checked it installs OK. Should be good to go. Thanks again!
