### ISSUE TITLE
Add scite.ai tally contextual citation data to supplement citations

### ISSUE THREAD

**Issue by domenicrosati** [nealhaddaway/citationchaser#12]
# Issue

We'd (scite.ai) like to contribute a PR that uses, optionally, scite.ai tally citation classification data (Supporting, Disputing, Mentioning) to help users and ourselves get better-contextualized citations.

@nealhaddaway Is this something you would be open to? 

Our current API docs are (https://documenter.getpostman.com/view/7840038/SzYaVdeo?version=latest#ece530f0-7316-457c-b48f-8205b4e9abb9) though we are working on newer ones.

**Comment by nealhaddaway** [comment]
Thanks, Domenic. I'm afraid I don't think it is - we specifically don't want reviewers to know information like that for a systematic review, so that's really not at all the aim of the tool.
But thanks for your interest!
Neal
________________________________

**Comment by domenicrosati** [comment]
Thanks that totally makes sense!
