### ISSUE TITLE
Unclear how to combine ?dois=/?pmids=etc as worked example contains only doi

### ISSUE THREAD

**Issue by jc2249** [nealhaddaway/citationchaser#14]
When running a review I often find I have mixed identifiers available for the included studies which I wish to review citations and references for. However, AMAZING though the citaitonchaser is, it would be even more amazing if we could run all included studies even with mixed identifiers, and find the list of all the Unique article IDs for citations for the complete group, instead of needing to download and then combine those for each ID type. Is it possible to add a note to the Readme explaining how to do this?

**Comment by jc2249** [comment]
(Using the shiny app https://estech.shinyapps.io/citationchaser/  so I'm referring to the text to developers there.

**Comment by nealhaddaway** [comment]
Thanks - it's not currently possible because it requires separate requests to the Lens.org API for each identifier set. It's indeed possible to input a list of identifiers with separate tags in the referral URL (.../?=dois=xxx,magids=xxx') but it requires quite a complicated rewrite of the Shiny App. It's on my to-do list but the list is long, sadly. Help much appreciated here, though, anyone else?! Thanks

**Comment by befriendabacterium** [comment]
Hi folks just used citationchaser to clean up a messy bibliography with missing fields and it worked excellently, thanks! Though I also had mixed IDs and was also about to post an issue about integrating ability to use mixed IDs, as I had to do DOI and PMCID identified articles separetly.

Playing around on Lens.Org I wondered whether you might be able to do this by using the query "citation_id:"INSERT_ID" in your queries? When you do this on their site, you can input either DOI or PMCID and it'll return the article. I assume there's a way to run this query via the API so just posting it here as an idea that might help integrate this functionality @nealhaddaway and @DrMattG ? 

Cheers
Matt

**Comment by nealhaddaway** [comment]
Heya - so I’ve got the combined identifiers working at
https://estech.shinyapps.io/citationchasertest

Enter the ids as …/?dois=…&pmids=…

Sent from my iPhone

On 3 Dec 2021, at 07:52, Matt Lloyd Jones ***@***.***> wrote:

﻿

Hi folks just used citationchaser to clean up a messy bibliography with missing fields and it worked excellently, thanks! Though I also had mixed IDs and was also about to post an issue about integrating ability to use mixed IDs, as I had to do DOI and PMCID identified articles separetly.

Playing around on Lens.Org I wondered whether you might be able to do this by using the query "citation_id:"INSERT_ID" in your queries? When you do this on their site, you can input either DOI or PMCID and it'll return the article. I assume there's a way to run this query via the API so just posting it here as an idea that might help integrate this functionality @nealhaddaway<https://github.com/nealhaddaway> and @DrMattG<https://github.com/DrMattG> ?

Cheers
Matt

**Comment by jc2249** [comment]
Great work!

**Comment by befriendabacterium** [comment]
Crikey blimey, that was fast

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nealhaddaway** [comment]
All done and sorted now.
