### ISSUE TITLE
Change license to GPL?

### ISSUE THREAD

**Issue by DrMattG** [nealhaddaway/citationchaser#15]
@nealhaddaway perhaps we should change the license to ensure derivatives have to be open source

**Comment by nealhaddaway** [comment]
Good idea!

Sent from my iPhone

On 26 Nov 2021, at 09:31, Matthew Grainger ***@***.***> wrote:

﻿

@nealhaddaway<https://github.com/nealhaddaway> perhaps we should change the license to ensure derivatives have to be open source

**Comment by nealhaddaway** [comment]
GPL seems appropriate here? https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633
[https://github.githubassets.com/images/modules/gists/gist-og-image.png]<https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633>
What you need to know to choose an open source license. · GitHub<https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633>
What you need to know to choose an open source license. - open_source_licenses.md
gist.github.com

________________________________
From: Matthew Grainger ***@***.***>
Sent: 26 November 2021 09:31
To: nealhaddaway/citationchaser ***@***.***>
Cc: nealhaddaway ***@***.***>; Mention ***@***.***>
Subject: [nealhaddaway/citationchaser] Change license to GPL? (Issue #15)


@nealhaddaway<https://github.com/nealhaddaway> perhaps we should change the license to ensure derivatives have to be open source
