### ISSUE TITLE
0 day issue

### ISSUE THREAD

**Issue by copariuc** [nealhaddaway/citationchaser#18]
Error: object 'vlookup' is not exported by 'namespace:expss' when I load package

**Comment by DrMattG** [comment]
Thanks @copariuc the developer of {expss} have moved vlookup to {maditr}. I have proposed a change to reflect that - if you can give us a day or so to check it works then we can let you know when it is back up and running (@nealhaddaway and I are in different timezones at the moment!). Sorry for the inconvenience.

[https://github.com/nealhaddaway/citationchaser/pull/19]

**Comment by DrMattG** [comment]
Hi again @copariuc. We have made the changes to the Shiny App: https://estech.shinyapps.io/citationchaser/ but we just need to check a few more things on the package itself before pushing the changes up to the main version. If you need the package you can install my branch (devtools::install_github("nealhaddaway/citationchaser", ref="DrMattG-patch-vlookup") and use that in the meantime. It might be a few days before we get the main branch fully tested.

**Comment by nealhaddaway** [comment]
All changes have now been ported across and that should be working fine.
