### ISSUE TITLE
Add argument to define number of steps [feature request]

### ISSUE THREAD

**Issue by mcguinlu** [nealhaddaway/citationchaser#3]
Hi @nealhaddaway,

As a feature request for this package, I would love to have an argument to define the number of steps away from the initial article(s) provided the function returns. So for example if `steps = 1` and `get_records = "citations"`, you get just the records cited by that reference. But if `steps = 2`, you get the records cited by that initial reference, and then records cited by the records cited by the original reference.

You can do this manually at the moment by taking the output of the initial run of the function and passing it back to `get_refs()`, but having it baked into the function (with appropriate deduplication) would be amazing!

**Comment by nealhaddaway** [comment]
Good idea - The Lens aren't too happy about overburdening the server, and you rapidly jump up to tens of thousands of hits when you jump more than one step away. I did initially build that in but took it out. I'm chatting to Lens today so will see if they think this is OK.
Thanks!
Neal
________________________________

**Comment by mcguinlu** [comment]
Awesome - sounds like you have it in hand! 😀
