### ISSUE TITLE
 Shinyapp version failed to load

### ISSUE THREAD

**Issue by tkwong94** [nealhaddaway/citationchaser#30]
I have used the Shiny app version a few times before. The last time I tried was about a month ago and it was working fine. However, it failed to load when I tried to open the app again today. Does anyone know why?

<img width="479" alt="image" src="https://github.com/nealhaddaway/citationchaser/assets/15152824/112577b2-80ff-4afc-9857-a5ff94e71b07">

**Comment by nealhaddaway** [comment]
Thanks so much for flagging this - the application needed to be reset and is working fine now.
Thanks!
Neal
